FROM python:3.7
WORKDIR /app

COPY requirements.txt api.py .flaskenv ./
RUN pip install --upgrade pip
RUN pip install --no-deps -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "api:app"]